---
title: "2018_144L Phyloseq anylysis"
author: "Christina Jimenez"
date: "11/18/2020"
output: github_document
---
# Intro

We explore the processed 2018_144l sequences using [phyloseq](https://joey711.github.io/phyloseq/)

# Install phyloseq

```{r}
# BiocManager::install("phyloseq")
```


```{r message = F, warning = F}
library(tidyverse) 
library(phyloseq)
library(RColorBrewer)
library(readxl)
```

# Import Data 

```{r message = F}
count.tab <- read_rds("~/Desktop/GITHUB/144l_students/Output_Data/week5/2018seqtab-nochimtaxa.rds") #table of counts for each sequence in each sample
tax.tab <- read_rds("~/Desktop/GITHUB/144l_students/Output_Data/week5/2018taxa.rds") #table that matches ASV to sequence

metadata <- read_excel("~/Desktop/GITHUB/144l_students/Input_Data/week3/144L_2018_BactAbund.xlsx", sheet = "Metadata")
subset <- metadata %>% 
  select(Treatment, Bottle, Timepoint, DNA_SampleID)
sample <- read_rds("~/Desktop/GITHUB/144l_students/Output_Data/week 4/144L_2018TOC.rds")

sample.tab <- left_join(sample, subset) %>% 
  drop_na(DNA_SampleID) %>%
  column_to_rownames(var = "DNA_SampleID") 
```

# Phyloseq Object


```{r}
OTU = otu_table(count.tab, taxa_are_rows = TRUE)
TAX = tax_table(tax.tab)
SAM = sample_data(sample.tab)
ps = phyloseq(OTU,TAX,SAM)
```

# Filter sequences


```{r}
sub_ps <- ps %>%
  subset_taxa(Family  != "mitochondria" & Order  != "Chloroplast")
```

# Sample Summary



```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 6, fig.align = "center"}
# Data frame with a column for the read counts of each sample
sample_sum_df <- data.frame(sum = sample_sums(sub_ps))
# Histogram 
ggplot(sample_sum_df, aes(x = sum)) + 
  geom_histogram(color = "black", fill = "#377EB8", binwidth = 2000) +
  ggtitle("Distribution of sample sequencing depth") + 
  xlab("Read counts") +
  theme(axis.title.y = element_blank()) +
  theme_bw()
```

```{r}
# mean, max and min of sample read counts
summary(sample_sum_df)
```


# Beta Diversity

## Subsample


```{r}
ps_min <-  rarefy_even_depth(sub_ps, sample.size = min(sample_sums(sub_ps)))
mean(sample_sums(sub_ps)) #28809
mean(sample_sums(ps_min)) #2064  
```


## NMDS


```{r}
set.seed(1)
# Ordinate
nmds <- ordinate(sub_ps, method = "NMDS",  distance = "bray") # stress = 0.07
```

```{r}
set.seed(1)
# Ordinate
nmds_min <- ordinate(ps_min, method = "NMDS",  distance = "bray") # stress = 0.08
```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align = "center"}
levels <- c("Control", "Ash Leachate", "Mud Leachate", "Glucose_Nitrate_Phosphate")

nmds.plot <- plot_ordination(sub_ps, nmds,  title = "NMDS") +
   geom_point(aes(fill = Datetime, shape = factor(Treatment, levels = levels)), alpha = 0.6, stroke = 2, size = 2) +
  scale_shape_manual(values = c(21, 22, 23, 24)) +
  scale_fill_gradient(low = "#377EB8", high = "#ffc425") +
  theme_bw() 

#removing one of the plotting layers 

nmds.plot$layers <- nmds.plot$layers[-1]
nmds.plot + 
  guides(fill = guide_colorbar(title = "Datetime"), shape = guide_legend(title = "Treatment"))
```

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align = "center"}
nmds_min.plot <- plot_ordination(ps_min, nmds_min,  title = "NMDS") +
   geom_point(aes(fill = Datetime, shape = factor(Treatment, levels = levels)), alpha = 0.6, stroke = 2, size = 2) +
  scale_shape_manual(values = c(21, 22, 23, 24)) +
  scale_fill_gradient(low = "#377EB8", high = "#ffc425") +
  theme_bw() 

#removing one of the plotting layers

nmds_min.plot$layers <- nmds_min.plot$layers[-1]
nmds_min.plot + 
  guides(fill = guide_colorbar(title = "Datetime"), shape = guide_legend(title = "Treatment"))
```


# Alpha Diversity


```{r}
richness <- estimate_richness(ps_min, measures = c("Chao1", "Shannon")) %>% 
  rownames_to_column(., var = "DNA_ID") %>% 
  mutate_at(vars(DNA_ID), str_replace_all, pattern = "X144", "144")
```


Let’s add the sample metadata into this dataframe 

```{r}
alphadiv <- left_join(richness, sample.tab %>% rownames_to_column(., var = "DNA_ID")) 
```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 9, fig.width = 16, fig.align = "center"}
# install.packages("ggpubr")
library(ggpubr)

pivot.data <- alphadiv %>% 
  select(Treatment, Bottle, Timepoint, days, Chao1, Shannon) %>% 
  pivot_longer(.,  cols = c(Chao1,  Shannon), names_to = "measure", values_to = "est" ) %>% 
  left_join(., alphadiv %>% 
              select(Treatment, Location, Bottle, Timepoint, days, se.chao1)) %>% 
  mutate(se.chao1 = ifelse(measure == "Chao1", se.chao1, NA)) 

alpha.plot <- ggboxplot(pivot.data, x = "Timepoint", y = "est",
            xlab = expression(italic(paste(""))), 
            ylab = expression(italic(paste("Alpha Diversity Measure"))),
            add = "dotplot",
            width = 0.2,
            ggtheme = theme_bw()) +  
  stat_compare_means(label.x = "6") +
  facet_grid(measure~ factor(Treatment, levels = levels), scales = "free") 

alpha.plot
```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 9, fig.width = 16, fig.align = "center"}
alpha.plot2 <-  ggboxplot(pivot.data, x = "Treatment", y = "est", 
            xlab = expression(italic(paste(""))), 
            ylab = expression(italic(paste("Alpha Diversity Measure"))),
            add = "dotplot",
            width = 0.2,
            ggtheme = theme_bw()) +  
  stat_compare_means(label.x = "Ash Leachate") +
  facet_grid(measure~Timepoint, scales = "free") 
alpha.plot2
```


# Generate relative abundances


```{r}
ps_std <- transform_sample_counts(ps_min, function(x) x/sum(x))
#extract the relative abundance table and coerce into dataframe
ps_std.tab <- as(otu_table(ps_std), "matrix")
ps_std.df = as.data.frame(ps_std.tab) 
```

# Make table

```{r warning = F}
#Taxa table into a data frame
tax.df <-  as.data.frame(tax.tab) 

#Combine data frames
custom.tab <- tax.df %>% 
  rownames_to_column(., var = "asv") %>% 
  left_join(., ps_std.df %>% rownames_to_column(., var = "asv")) %>% 
  #New index of that combines the  class, order, family, and genus values
  mutate(pco = paste(Phylum, "_", Class, "_", Order)) %>% 
  select(-c(asv:Genus)) %>% 
  select(pco,everything()) %>% 
  group_by(pco) %>% 
  summarise_at(vars(contains(c("144"))), sum, na.rm = T) %>% 
  ungroup()

#Row names into column names
colnames <- custom.tab[,1] 
#transpose the dataframe

t_custom.tab <-  as.data.frame(t(custom.tab[,-1]))
colnames(t_custom.tab) <- colnames$pco

#merge
sweet.tab <- t_custom.tab %>% 
  rownames_to_column(., var = "sample") %>% 
  left_join(., sample.tab %>% rownames_to_column(., var = "sample") %>% select(sample, Experiment, Bottle, Treatment, Timepoint, days, cells)) %>% 
  select(sample, Experiment:cells, everything())

relabund <- sweet.tab %>% 
  select(-c(sample:cells)) %>% 
  .[, order(colSums(-.))] %>% 
  bind_cols(sweet.tab %>% select(sample:cells), .)
```

## Heatmap

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 16, fig.width = 10, fig.align = "center"}
relaheat.data <- relabund %>% 
  select(-c(sample, Experiment, Bottle, days, cells)) %>%
  pivot_longer(.,-c(Treatment:Timepoint), names_to = "taxa", values_to = "relabund") %>% 
  separate(taxa, into = c("p", "c", "o"), sep = " _ ") %>% 
  group_by(Treatment, Timepoint, p, c, o) %>% 
  mutate(mean_relabund = mean(relabund, na.rm = T)) %>% 
  ungroup() %>% 
  select(-relabund) %>% 
  distinct()

#install.packages("viridis")
library(viridis)
relaheat <- relaheat.data %>%
  ggplot(aes(x = Timepoint, y = o)) +
  geom_tile(aes(fill = mean_relabund), color = "white") +
  scale_fill_viridis(option = "D") +
  labs(x = "Timepoint", y = "Order", fill = "Relative Abundance") +
facet_grid(~factor(Treatment, levels = levels)) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 12),
        legend.position = "top") +
   guides(fill = guide_colourbar(barheight = 2, barwidth = 20, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1), color = F) 
relaheat
```


# Save and knit

```{r}
saveRDS(sweet.tab, "~/Desktop/GITHUB/144l_students/Output_Data/week6/Custom_ASV_Table.rds")
saveRDS(sub_ps, "~/Desktop/GITHUB/144l_students/Output_Data/week6/phyloseq_obj.rds")
saveRDS(ps_min, "~/Desktop/GITHUB/144l_students/Output_Data/week6/subsampled_phyloseq_obj.rds")
saveRDS(alphadiv, "~/Desktop/GITHUB/144l_students/Output_Data/week6/alphadiv.rds")
```


# Stacked Barplots

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center"}
relabar.data <- relabund %>% 
  select(-c(sample, Experiment, days, cells)) %>%
  pivot_longer(.,-c(Bottle:Timepoint), names_to = "taxa", values_to = "relabund") %>% 
  group_by(Treatment, Timepoint, taxa) %>% 
  mutate(mean_relabund = mean(relabund, na.rm = T)) %>% 
  ungroup() %>% 
  separate(taxa, into = c("p", "c", "o"), sep = " _ ") %>% 
  select(Treatment, Timepoint, p, c, o, mean_relabund) %>% 
  distinct() 
# Plot 
relabar.data %>% 
  mutate(Timepoint = as.character(Timepoint)) %>% 
  ggplot(., aes(x =  Timepoint, y = mean_relabund)) + 
  geom_bar(aes(fill = o), color = "black", stat = "identity", position = "stack", width = 0.25, stroke = 1) +
  labs(x = "Timepoint", y = "Relative Abundance") +
  theme_bw() +
  guides(fill = guide_legend(reverse = TRUE, keywidth = 1, kerheight = 1, title = "Order")) +
  facet_grid(~factor(Treatment, levels = levels))
```


```{r}
saveRDS(relabar.data, "~/Desktop/GITHUB/144l_students/Output_Data/week6/relabar_data.rds")
```



